// Accepted VIPER logo family (doc/design/visual-manifest.md). Web-sized copies generated by
// scripts/optimize-brand-assets.js from the handoff originals; alpha preserved, no background box.
import lockupBlack from '../assets/brand/viper-lockup-black.png'
import lockupWhite from '../assets/brand/viper-lockup-white.png'
import markBlack from '../assets/brand/viper-mark-black.png'
import markBlackNeonGreen from '../assets/brand/viper-mark-black-neon-green.png'
import markNeonGreenBlack from '../assets/brand/viper-mark-neon-green-black.png'
import markWhite from '../assets/brand/viper-mark-white.png'
import type { Theme } from '../theme/theme'

// mark    — icon only: collapsed sidebar, small icon contexts (favicons are static files in public/).
// lockup  — icon + VIPER wordmark: expanded sidebar, login, about.
// accent  — neon mark for hero/premium moments; never as the everyday navigation logo.
export type LogoVariant = 'mark' | 'lockup' | 'accent'

// Picks the file that contrasts with the theme's canvas: white art on dark, black art on light. For the accent,
// the neon-dominant mark reads on dark; on light the black mark with neon edges keeps the silhouette legible.
const LOGOS: Record<LogoVariant, Record<Theme, string>> = {
  mark: { dark: markWhite, light: markBlack },
  lockup: { dark: lockupWhite, light: lockupBlack },
  accent: { dark: markNeonGreenBlack, light: markBlackNeonGreen },
}

export function logoSource(variant: LogoVariant, theme: Theme): string {
  return LOGOS[variant][theme]
}
