import { execFileSync } from 'node:child_process'

import { expect, type Page, test } from '@playwright/test'

import { BACKEND_DIR, PYTHON } from './env'

// Rows a test owns (decision I-81). Specs run fully parallel, in any order, on one shared E2E database: the synthetic
// dataset loaded by global setup is read-only for them, and every row a test writes is its own, named with
// `uniqueSuffix()`, so neither a concurrent test nor a repeated run of the same test ever sees or collides with it.

let created = 0

// Unique within the run (global setup rebuilds the database for every run): the worker index, never reused within a
// run, and a per-worker counter. Fixed width, so no suffix is a prefix of another; digits only, so it also fits in a
// synthetic SIREN.
export function uniqueSuffix(): string {
  created += 1
  return `${String(test.info().workerIndex).padStart(2, '0')}${String(created).padStart(3, '0')}`
}

// Appends the Luhn check digit that SIREN and SIRET numbers carry.
function withCheckDigit(body: string): string {
  let sum = 0
  for (let index = 0; index < body.length; index += 1) {
    // From the right, every other digit is doubled, starting next to the check digit.
    const value = Number(body[body.length - 1 - index]) * (index % 2 === 0 ? 2 : 1)
    sum += value > 9 ? value - 9 : value
  }
  return `${body}${String((10 - (sum % 10)) % 10)}`
}

// A SIREN with a valid check digit, 999 followed by the suffix, as used by no other test of the run.
export function syntheticSiren(suffix: string): string {
  return withCheckDigit(`999${suffix}`)
}

// SIRET number `nic` (1-9999) of that SIREN, with its check digit.
export function syntheticSiret(siren: string, nic: number): string {
  return withCheckDigit(`${siren}${String(nic).padStart(4, '0')}`)
}

async function csrfToken(page: Page): Promise<string> {
  const session = await page.request.get('/api/auth/session')
  expect(session.ok()).toBe(true)
  return ((await session.json()) as { csrf_token: string }).csrf_token
}

// Writes through the real, audited API as the signed-in page (its session cookie and CSRF token).
async function post<T>(page: Page, path: string, data: object): Promise<T> {
  const response = await page.request.post(path, { data, headers: { 'X-CSRF-Token': await csrfToken(page) } })
  expect(response.ok(), await response.text()).toBe(true)
  return (await response.json()) as T
}

export interface CompanySeed {
  display_name: string
  legal_name?: string
  siren?: string
  website_url?: string
  email_domain?: string
  size_label?: string
  establishments?: { name: string; siret: string; city: string; kind?: string; is_primary: boolean }[]
}

export function createCompany(page: Page, company: CompanySeed): Promise<{ id: string }> {
  return post(page, '/api/companies', company)
}

export function createReferent(page: Page, referent: { first_name: string; last_name: string; email: string | null }) {
  return post<{ id: string }>(page, '/api/settings/referents', referent)
}

// One row of the legacy workbook, by the short keys of backend/tests/fixtures/synthetic/legacy_workbook.py (`company`,
// `civility`, `last_name`, `first_name`, `job`, `email`, `phone`, `mobile`, `week`, `referent`, `rdv`, `relance1`…).
export type WorkbookRow = Record<string, string | number | undefined>

// A synthetic workbook in the historical layout, generated by the backend fixture (never written to disk).
export function syntheticWorkbook(rows: WorkbookRow[]): Buffer {
  const script = [
    'import base64, json, sys',
    'from tests.fixtures.synthetic.legacy_workbook import legacy_xlsx',
    'sys.stdout.write(base64.b64encode(legacy_xlsx(json.loads(sys.argv[1]))).decode())',
  ].join('\n')
  const output = execFileSync(PYTHON, ['-c', script, JSON.stringify(rows)], { cwd: BACKEND_DIR })
  return Buffer.from(output.toString(), 'base64')
}

interface ImportReviewAnswer {
  review: { digest: string; preview: { summary: { file_fingerprint: string } }; weeks: { key: string; week: number }[] }
}

// Imports prospects through the real import API (preview, then commit with the default decisions), giving every
// week written without a year (`S37`) its year from `weekYears` (week number → year). Returns the batch id.
// A company another test creates meanwhile with a close name is a new candidate that outdates the review (409
// `preview_outdated`, the server is right): like « Relancer l'analyse » in the UI, the file is analysed again.
export async function importProspects(
  page: Page,
  name: string,
  rows: WorkbookRow[],
  weekYears: Record<number, number> = {},
): Promise<string> {
  const mimeType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
  const file = { name, mimeType, buffer: syntheticWorkbook(rows) }
  const headers = { 'X-CSRF-Token': await csrfToken(page) }
  for (let attempt = 1; ; attempt += 1) {
    const preview = await page.request.post('/api/imports/preview', { multipart: { file }, headers })
    expect(preview.ok(), await preview.text()).toBe(true)
    const { review } = (await preview.json()) as ImportReviewAnswer
    const decisions = {
      file_fingerprint: review.preview.summary.file_fingerprint,
      preview_digest: review.digest,
      legal_basis_or_collection_context: 'Données synthétiques de test E2E',
      weeks: Object.fromEntries(review.weeks.map((group) => [group.key, weekYears[group.week] ?? null])),
    }
    const commit = await page.request.post('/api/imports/commit', {
      multipart: { file, decisions: JSON.stringify(decisions) },
      headers,
    })
    const answer = await commit.text()
    if (commit.status() === 409 && answer.includes('preview_outdated') && attempt < 3) continue
    expect(commit.ok(), answer).toBe(true)
    return (JSON.parse(answer) as { batch: { id: string } }).batch.id
  }
}
